site_name: Python Easyverein Documentation
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            unwrap_annotated: true

markdown_extensions:
  - toc:
      toc_depth: 4

nav:
  - index.md
  - usage.md
  - api.md
